"""Claude Code provider presets (converted from cc-switch TypeScript)."""

CLAUDE_PRESETS = [
    {
        "id": "claude-official",
        "name": "Claude Official",
        "category": "official",
        "website_url": "https://www.anthropic.com/claude-code",
        "icon": "anthropic",
        "icon_color": "#D4915D",
        "settings_config": {"env": {}},
        "api_format": None,
    },
    {
        "id": "shengsuanyun",
        "name": "Shengsuanyun",
        "category": "aggregator",
        "website_url": "https://www.shengsuanyun.com",
        "icon": "shengsuanyun",
        "icon_color": None,
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://router.shengsuanyun.com/api",
            "ANTHROPIC_AUTH_TOKEN": "",
        }},
        "api_format": None,
    },
    {
        "id": "gemini-native",
        "name": "Gemini Native",
        "category": "third_party",
        "website_url": "https://ai.google.dev/gemini-api",
        "icon": "gemini",
        "icon_color": "#4285F4",
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://generativelanguage.googleapis.com",
            "ANTHROPIC_API_KEY": "",
            "ANTHROPIC_MODEL": "gemini-3.1-pro",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "gemini-3-flash",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "gemini-3.1-pro",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "gemini-3.1-pro",
        }},
        "api_format": "gemini_native",
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "category": "cn_official",
        "website_url": "https://platform.deepseek.com",
        "icon": "deepseek",
        "icon_color": "#1E88E5",
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://api.deepseek.com/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "deepseek-v4-pro",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "deepseek-v4-flash",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "deepseek-v4-pro",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "deepseek-v4-pro",
        }},
        "api_format": None,
    },
    {
        "id": "zhipu-glm",
        "name": "Zhipu GLM",
        "category": "cn_official",
        "website_url": "https://open.bigmodel.cn",
        "icon": "zhipu",
        "icon_color": "#0F62FE",
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://open.bigmodel.cn/api/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "glm-5",
        }},
        "api_format": None,
    },
    {
        "id": "zhipu-glm-en",
        "name": "Zhipu GLM (z.ai)",
        "category": "cn_official",
        "website_url": "https://z.ai",
        "icon": "zhipu",
        "icon_color": "#0F62FE",
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://api.z.ai/api/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "glm-5",
        }},
        "api_format": None,
    },
    {
        "id": "bailian",
        "name": "Bailian",
        "category": "cn_official",
        "website_url": "https://bailian.console.aliyun.com",
        "icon": "bailian",
        "icon_color": "#624AFF",
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://dashscope.aliyuncs.com/apps/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
        }},
        "api_format": None,
    },
    {
        "id": "kimi",
        "name": "Kimi",
        "category": "cn_official",
        "website_url": "https://platform.moonshot.cn",
        "icon": "kimi",
        "icon_color": None,
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://api.moonshot.cn/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "kimi-k2.6",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "kimi-k2.6",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "kimi-k2.6",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "kimi-k2.6",
        }},
        "api_format": None,
    },
    {
        "id": "stepfun",
        "name": "StepFun",
        "category": "cn_official",
        "website_url": "https://platform.stepfun.com",
        "icon": "stepfun",
        "icon_color": None,
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://api.stepfun.com/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "step-3.5-flash",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "step-3.5-flash",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "step-3.5-flash",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "step-3.5-flash",
        }},
        "api_format": None,
    },
    {
        "id": "minimax",
        "name": "MiniMax",
        "category": "cn_official",
        "website_url": "https://platform.minimax.io",
        "icon": "minimax",
        "icon_color": None,
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://api.minimax.chat/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "minimax-m2.7",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "minimax-m2.5-lightning",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "minimax-m2.7",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "minimax-m2.7",
        }},
        "api_format": None,
    },
    {
        "id": "doubao-seed",
        "name": "DouBao Seed",
        "category": "cn_official",
        "website_url": "https://console.volcengine.com/ark",
        "icon": "doubao",
        "icon_color": None,
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://ark.cn-beijing.volces.com/api/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "doubao-seed-code",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "doubao-seed-code",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "doubao-seed-code",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "doubao-seed-code",
        }},
        "api_format": None,
    },
    {
        "id": "siliconflow",
        "name": "SiliconFlow",
        "category": "aggregator",
        "website_url": "https://cloud.siliconflow.cn",
        "icon": "siliconflow",
        "icon_color": None,
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://api.siliconflow.cn/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
        }},
        "api_format": None,
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "category": "aggregator",
        "website_url": "https://openrouter.ai",
        "icon": "openrouter",
        "icon_color": None,
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://openrouter.ai/api/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
        }},
        "api_format": None,
    },
    {
        "id": "aihubmix",
        "name": "AiHubMix",
        "category": "aggregator",
        "website_url": "https://aihubmix.com",
        "icon": "aihubmix",
        "icon_color": None,
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://aihubmix.com/anthropic",
            "ANTHROPIC_API_KEY": "",
        }},
        "api_format": None,
    },
    {
        "id": "nvidia",
        "name": "NVIDIA NIM",
        "category": "aggregator",
        "website_url": "https://build.nvidia.com",
        "icon": "nvidia",
        "icon_color": "#76B900",
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://integrate.api.nvidia.com",
            "ANTHROPIC_AUTH_TOKEN": "",
        }},
        "api_format": "openai_chat",
    },
    {
        "id": "aws-bedrock-aksk",
        "name": "AWS Bedrock (AKSK)",
        "category": "cloud_provider",
        "website_url": "https://aws.amazon.com/bedrock",
        "icon": "aws",
        "icon_color": "#FF9900",
        "settings_config": {"env": {
            "CLAUDE_CODE_USE_BEDROCK": "1",
            "AWS_ACCESS_KEY_ID": "",
            "AWS_SECRET_ACCESS_KEY": "",
            "AWS_REGION": "us-east-1",
        }},
        "api_format": None,
    },
    {
        "id": "github-copilot",
        "name": "GitHub Copilot",
        "category": "third_party",
        "website_url": "https://github.com/features/copilot",
        "icon": "github",
        "icon_color": None,
        "settings_config": {"env": {}},
        "api_format": "openai_chat",
    },
    {
        "id": "xiaomi-mimo",
        "name": "Xiaomi MiMo",
        "category": "cn_official",
        "website_url": "https://xiaomimiai.github.io",
        "icon": "mimo",
        "icon_color": None,
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://api.maimiao.com/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "mimo-v2-flash",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "mimo-v2-flash",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "mimo-v2-pro",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "mimo-v2-pro",
        }},
        "api_format": None,
    },
    {
        "id": "longcat",
        "name": "Longcat",
        "category": "cn_official",
        "website_url": "https://cloud.longcat.ae",
        "icon": "longcat",
        "icon_color": None,
        "settings_config": {"env": {
            "ANTHROPIC_BASE_URL": "https://cloud.longcat.ae/api/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "CLAUDE_CODE_MAX_OUTPUT_TOKENS": "64000",
            "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1",
        }},
        "api_format": None,
    },
]
