"""Gemini Code provider presets (converted from cc-switch TypeScript)."""

GEMINI_PRESETS = [
    {
        "id": "gemini-official",
        "name": "Google Official",
        "category": "official",
        "website_url": "https://ai.google.dev/",
        "icon": "gemini",
        "icon_color": "#4285F4",
        "settings_config": {"env": {}},
    },
    {
        "id": "packycode",
        "name": "PackyCode",
        "category": "third_party",
        "website_url": "https://www.packyapi.ai",
        "icon": "packycode",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://www.packyapi.ai",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "apinebula",
        "name": "APINebula",
        "category": "third_party",
        "website_url": "https://apinebula.ai",
        "icon": "apinebula",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://apinebula.ai",
            "GEMINI_API_KEY": "",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "aicodemirror",
        "name": "AICodeMirror",
        "category": "third_party",
        "website_url": "https://www.aicodemirror.ai",
        "icon": "aicodemirror",
        "icon_color": "#000000",
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://api.aicodemirror.ai/api/gemini",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "shengsuanyun",
        "name": "Shengsuanyun",
        "category": "aggregator",
        "website_url": "https://www.shengsuanyun.com",
        "icon": "shengsuanyun",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://router.shengsuanyun.com/api",
            "GEMINI_MODEL": "google/gemini-3.6-flash",
        }},
    },
    {
        "id": "aigocode",
        "name": "AIGoCode",
        "category": "third_party",
        "website_url": "https://aigocode.app",
        "icon": "aigocode",
        "icon_color": "#5B7FFF",
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://api.aigocode.app",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "qiniu",
        "name": "Qiniu",
        "category": "aggregator",
        "website_url": "https://s.qiniu.com/nMvAvy",
        "icon": "qiniu",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://api.qnaigc.com/bypass/vertex",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "aicoding",
        "name": "AICoding",
        "category": "third_party",
        "website_url": "https://aicoding.inc",
        "icon": "aicoding",
        "icon_color": "#000000",
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://api.aicoding.inc",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "subrouter",
        "name": "SubRouter",
        "category": "aggregator",
        "website_url": "https://subrouter.ai",
        "icon": "subrouter",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://subrouter.ai/v1beta",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "apikeyfun",
        "name": "APIKEY.FUN",
        "category": "third_party",
        "website_url": "https://apikey.fun",
        "icon": "apikeyfun",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://api.apikey.fun",
            "GEMINI_API_KEY": "",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "code0",
        "name": "Code0",
        "category": "aggregator",
        "website_url": "https://code0.ai",
        "icon": "code0",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://code0.ai",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "a6api",
        "name": "A6API",
        "category": "aggregator",
        "website_url": "https://www.a6api.com",
        "icon": "a6api",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://api.a6api.com",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "sssaicode",
        "name": "SSSAiCode",
        "category": "third_party",
        "website_url": "https://sssaicodeapi.com",
        "icon": "sssaicode",
        "icon_color": "#000000",
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://node-hk.sssaicodeapi.com/api",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "etok",
        "name": "ETok.ai",
        "category": "third_party",
        "website_url": "https://etok.ai",
        "icon": "etok",
        "icon_color": "#000000",
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://api.etok.ai/v1beta",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "cubence",
        "name": "Cubence",
        "category": "third_party",
        "website_url": "https://cubence.com",
        "icon": "cubence",
        "icon_color": "#000000",
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://api.cubence.com",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "crazyrouter",
        "name": "CrazyRouter",
        "category": "third_party",
        "website_url": "https://www.crazyrouter.com",
        "icon": "crazyrouter",
        "icon_color": "#000000",
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://cn.crazyrouter.com",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "sudocode-us",
        "name": "SudoCode.us",
        "category": "third_party",
        "website_url": "https://sudocode.us",
        "icon": "sudocode-us",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://sudocode.us",
            "GEMINI_API_KEY": "",
            "GEMINI_MODEL": "gemini-3.1-flash-lite",
        }},
    },
    {
        "id": "xycai",
        "name": "XycAi",
        "category": "aggregator",
        "website_url": "https://xycai.us",
        "icon": "xycai",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://apicdn.xycai.us",
            "GEMINI_API_KEY": "",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "eflowcode",
        "name": "E-FlowCode",
        "category": "third_party",
        "website_url": "https://e-flowcode.cc",
        "icon": "eflowcode",
        "icon_color": "#000000",
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://e-flowcode.cc",
            "GEMINI_API_KEY": "",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "cherryin",
        "name": "CherryIN",
        "category": "aggregator",
        "website_url": "https://open.cherryin.ai",
        "icon": "cherryin",
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://open.cherryin.net",
            "GEMINI_API_KEY": "",
            "GEMINI_MODEL": "google/gemini-3.6-flash",
        }},
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "category": "aggregator",
        "website_url": "https://openrouter.ai",
        "icon": "openrouter",
        "icon_color": "#6566F1",
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://openrouter.ai/api",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "therouter",
        "name": "TheRouter",
        "category": "aggregator",
        "website_url": "https://therouter.ai",
        "icon": None,
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://api.therouter.ai",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
    {
        "id": "custom",
        "name": "Custom Provider",
        "category": "custom",
        "website_url": None,
        "icon": None,
        "icon_color": None,
        "settings_config": {"env": {
            "GOOGLE_GEMINI_BASE_URL": "https://api.example.com",
            "GEMINI_MODEL": "gemini-3.6-flash",
        }},
    },
]
