"""Pi provider presets (converted from cc-switch TypeScript piProviderPresets)."""

PI_PRESETS = [
    {
        "id": "kimi",
        "name": "Kimi",
        "category": "cn_official",
        "website_url": "https://platform.kimi.com?aff=cc-switch",
        "icon": "kimi",
        "icon_color": "#6366F1",
        "settings_config": {
            "name": "Kimi",
            "baseUrl": "https://api.moonshot.cn/v1",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "kimi-k2.7-code",
                    "name": "Kimi K2.7 Code",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 262144,
                    "maxTokens": 262144,
                    "thinkingLevelMap": {"off": None},
                },
                {
                    "id": "kimi-k3",
                    "name": "Kimi K3",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1048576,
                    "maxTokens": 131072,
                    "compat": {
                        "supportsStore": False,
                        "supportsDeveloperRole": False,
                        "supportsReasoningEffort": True,
                        "maxTokensField": "max_tokens",
                        "supportsStrictMode": False,
                        "thinkingFormat": "openai",
                        "requiresReasoningContentOnAssistantMessages": True,
                        "deferredToolsMode": "kimi",
                    },
                    "thinkingLevelMap": {
                        "off": None,
                        "minimal": None,
                        "low": "low",
                        "medium": None,
                        "high": "high",
                        "xhigh": None,
                        "max": "max",
                    },
                },
            ],
        },
    },
    {
        "id": "kimi-for-coding",
        "name": "Kimi For Coding",
        "category": "cn_official",
        "website_url": "https://www.kimi.com/code/?aff=cc-switch",
        "icon": "kimi",
        "icon_color": "#6366F1",
        "settings_config": {
            "name": "Kimi For Coding",
            "baseUrl": "https://api.kimi.com/coding",
            "api": "anthropic-messages",
            "apiKey": "",
            "models": [
                {
                    "id": "kimi-for-coding",
                    "name": "Kimi For Coding",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 262144,
                    "maxTokens": 32768,
                    "thinkingLevelMap": {},
                },
            ],
        },
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "category": "cn_official",
        "website_url": "https://platform.deepseek.com",
        "icon": "deepseek",
        "icon_color": "#1E88E5",
        "settings_config": {
            "name": "DeepSeek",
            "baseUrl": "https://api.deepseek.com/v1",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "deepseek-v4-pro",
                    "name": "DeepSeek V4 Pro",
                    "reasoning": True,
                    "input": ["text"],
                    "contextWindow": 1000000,
                    "maxTokens": 384000,
                    "thinkingLevelMap": {
                        "minimal": None,
                        "low": None,
                        "medium": None,
                        "high": "high",
                        "max": "max",
                    },
                },
                {
                    "id": "deepseek-v4-flash",
                    "name": "DeepSeek V4 Flash",
                    "reasoning": True,
                    "input": ["text"],
                    "contextWindow": 1000000,
                    "maxTokens": 384000,
                    "thinkingLevelMap": {
                        "minimal": None,
                        "low": None,
                        "medium": None,
                        "high": "high",
                        "max": "max",
                    },
                },
            ],
        },
    },
    {
        "id": "zhipu-glm",
        "name": "Zhipu GLM",
        "category": "cn_official",
        "website_url": "https://open.bigmodel.cn",
        "icon": "zhipu",
        "icon_color": "#0F62FE",
        "settings_config": {
            "name": "Zhipu GLM",
            "baseUrl": "https://open.bigmodel.cn/api/coding/paas/v4",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "glm-5.1",
                    "name": "GLM-5.1",
                    "reasoning": True,
                    "input": ["text"],
                    "contextWindow": 200000,
                    "maxTokens": 131072,
                    "thinkingLevelMap": {},
                },
            ],
        },
    },
    {
        "id": "zhipu-glm-en",
        "name": "Zhipu GLM en",
        "category": "cn_official",
        "website_url": "https://z.ai",
        "icon": "zhipu",
        "icon_color": "#0F62FE",
        "settings_config": {
            "name": "Zhipu GLM en",
            "baseUrl": "https://api.z.ai/api/coding/paas/v4",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "glm-5.1",
                    "name": "GLM-5.1",
                    "reasoning": True,
                    "input": ["text"],
                    "contextWindow": 200000,
                    "maxTokens": 131072,
                    "thinkingLevelMap": {},
                },
            ],
        },
    },
    {
        "id": "bailian",
        "name": "Bailian",
        "category": "cn_official",
        "website_url": "https://bailian.console.aliyun.com",
        "icon": "bailian",
        "icon_color": "#624AFF",
        "settings_config": {
            "name": "Bailian",
            "baseUrl": "https://dashscope.aliyuncs.com/compatible-mode/v1",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "qwen3-coder-plus",
                    "name": "Qwen3 Coder Plus",
                    "reasoning": False,
                    "input": ["text"],
                    "contextWindow": 1000000,
                    "maxTokens": 65536,
                },
            ],
        },
    },
    {
        "id": "volcengine-agentplan",
        "name": "火山Agentplan",
        "category": "cn_official",
        "website_url": "https://www.volcengine.com/activity/codingplan?ac=MMAP8JTTCAQ2&rc=6J6FV5N2&utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        "icon": "huoshan",
        "icon_color": "#3370FF",
        "settings_config": {
            "name": "火山Agentplan",
            "baseUrl": "https://ark.cn-beijing.volces.com/api/coding/v3",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "ark-code-latest",
                    "name": "Ark Code Latest",
                    "reasoning": False,
                    "input": ["text"],
                    "contextWindow": 128000,
                    "maxTokens": 16384,
                },
            ],
        },
    },
    {
        "id": "minimax",
        "name": "MiniMax",
        "category": "cn_official",
        "website_url": "https://platform.minimaxi.com",
        "icon": "minimax",
        "icon_color": "#FF6B6B",
        "settings_config": {
            "name": "MiniMax",
            "baseUrl": "https://api.minimaxi.com/v1",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "MiniMax-M2.7",
                    "name": "MiniMax-M2.7",
                    "reasoning": True,
                    "input": ["text"],
                    "contextWindow": 204800,
                    "maxTokens": 131072,
                    "thinkingLevelMap": {},
                },
            ],
        },
    },
    {
        "id": "modelscope",
        "name": "ModelScope",
        "category": "aggregator",
        "website_url": "https://modelscope.cn",
        "icon": "modelscope",
        "icon_color": "#624AFF",
        "settings_config": {
            "name": "ModelScope",
            "baseUrl": "https://api-inference.modelscope.cn/v1",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "ZhipuAI/GLM-5.2",
                    "name": "GLM-5.2",
                    "reasoning": True,
                    "input": ["text"],
                    "contextWindow": 1000000,
                    "maxTokens": 131072,
                    "thinkingLevelMap": {},
                },
            ],
        },
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "category": "aggregator",
        "website_url": "https://openrouter.ai",
        "icon": "openrouter",
        "icon_color": "#6566F1",
        "settings_config": {
            "name": "OpenRouter",
            "baseUrl": "https://openrouter.ai/api",
            "api": "anthropic-messages",
            "apiKey": "",
            "models": [
                {
                    "id": "anthropic/claude-sonnet-5",
                    "name": "Claude Sonnet 5",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1000000,
                    "maxTokens": 128000,
                    "compat": {"forceAdaptiveThinking": True},
                    "thinkingLevelMap": {"xhigh": "xhigh", "max": "max"},
                },
                {
                    "id": "anthropic/claude-opus-5",
                    "name": "Claude Opus 5",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1000000,
                    "maxTokens": 128000,
                    "compat": {"forceAdaptiveThinking": True},
                    "thinkingLevelMap": {"xhigh": "xhigh", "max": "max"},
                },
            ],
        },
    },
    {
        "id": "aihubmix",
        "name": "AiHubMix",
        "category": "aggregator",
        "website_url": "https://aihubmix.com",
        "icon": "aihubmix",
        "icon_color": "#006FFB",
        "settings_config": {
            "name": "AiHubMix",
            "baseUrl": "https://aihubmix.com",
            "api": "anthropic-messages",
            "apiKey": "",
            "models": [
                {
                    "id": "claude-sonnet-5",
                    "name": "Claude Sonnet 5",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1000000,
                    "maxTokens": 128000,
                    "compat": {"forceAdaptiveThinking": True},
                    "thinkingLevelMap": {"xhigh": "xhigh", "max": "max"},
                },
                {
                    "id": "claude-opus-5",
                    "name": "Claude Opus 5",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1000000,
                    "maxTokens": 128000,
                    "compat": {"forceAdaptiveThinking": True},
                    "thinkingLevelMap": {"xhigh": "xhigh", "max": "max"},
                },
            ],
        },
    },
    {
        "id": "therouter",
        "name": "TheRouter",
        "category": "aggregator",
        "website_url": "https://therouter.ai",
        "icon": None,
        "icon_color": None,
        "settings_config": {
            "name": "TheRouter",
            "baseUrl": "https://api.therouter.ai/v1",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "anthropic/claude-sonnet-5",
                    "name": "Claude Sonnet 5",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1000000,
                    "maxTokens": 128000,
                    "thinkingLevelMap": {},
                },
                {
                    "id": "openai/gpt-5.3-codex",
                    "name": "GPT-5.3 Codex",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 400000,
                    "maxTokens": 128000,
                    "thinkingLevelMap": {},
                },
                {
                    "id": "openai/gpt-5.2",
                    "name": "GPT-5.2",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 400000,
                    "maxTokens": 128000,
                    "thinkingLevelMap": {},
                },
                {
                    "id": "google/gemini-3.6-flash",
                    "name": "Gemini 3.6 Flash",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1048576,
                    "maxTokens": 65536,
                    "thinkingLevelMap": {},
                },
            ],
        },
    },
    {
        "id": "novita-ai",
        "name": "Novita AI",
        "category": "aggregator",
        "website_url": "https://novita.ai",
        "icon": "novita",
        "icon_color": "#000000",
        "settings_config": {
            "name": "Novita AI",
            "baseUrl": "https://api.novita.ai/openai",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "zai-org/glm-5.1",
                    "name": "GLM-5.1",
                    "reasoning": True,
                    "input": ["text"],
                    "contextWindow": 200000,
                    "maxTokens": 131072,
                    "thinkingLevelMap": {},
                },
            ],
        },
    },
    {
        "id": "packycode",
        "name": "PackyCode",
        "category": "third_party",
        "website_url": "https://www.packyapi.ai",
        "icon": "packycode",
        "icon_color": None,
        "settings_config": {
            "name": "PackyCode",
            "baseUrl": "https://www.packyapi.ai",
            "api": "anthropic-messages",
            "apiKey": "",
            "models": [
                {
                    "id": "claude-sonnet-5",
                    "name": "Claude Sonnet 5",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1000000,
                    "maxTokens": 128000,
                    "compat": {"forceAdaptiveThinking": True},
                    "thinkingLevelMap": {"xhigh": "xhigh", "max": "max"},
                },
                {
                    "id": "claude-opus-5",
                    "name": "Claude Opus 5",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1000000,
                    "maxTokens": 128000,
                    "compat": {"forceAdaptiveThinking": True},
                    "thinkingLevelMap": {"xhigh": "xhigh", "max": "max"},
                },
            ],
        },
    },
    {
        "id": "aicodemirror",
        "name": "AICodeMirror",
        "category": "third_party",
        "website_url": "https://www.aicodemirror.ai",
        "icon": "aicodemirror",
        "icon_color": "#000000",
        "settings_config": {
            "name": "AICodeMirror",
            "baseUrl": "https://api.aicodemirror.ai/api/claudecode",
            "api": "anthropic-messages",
            "apiKey": "",
            "models": [
                {
                    "id": "claude-sonnet-5",
                    "name": "Claude Sonnet 5",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1000000,
                    "maxTokens": 128000,
                    "compat": {"forceAdaptiveThinking": True},
                    "thinkingLevelMap": {"xhigh": "xhigh", "max": "max"},
                },
                {
                    "id": "claude-opus-5",
                    "name": "Claude Opus 5",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 1000000,
                    "maxTokens": 128000,
                    "compat": {"forceAdaptiveThinking": True},
                    "thinkingLevelMap": {"xhigh": "xhigh", "max": "max"},
                },
            ],
        },
    },
    {
        "id": "opencode-go",
        "name": "OpenCode Go",
        "category": "third_party",
        "website_url": "https://opencode.ai/go",
        "icon": "opencode",
        "icon_color": "#211E1E",
        "settings_config": {
            "name": "OpenCode Go",
            "baseUrl": "https://opencode.ai/zen/go/v1",
            "api": "openai-completions",
            "apiKey": "",
            "models": [
                {
                    "id": "glm-5.2",
                    "name": "GLM 5.2",
                    "reasoning": True,
                    "input": ["text"],
                    "contextWindow": 1000000,
                    "maxTokens": 131072,
                    "compat": {
                        "supportsStore": False,
                        "supportsDeveloperRole": False,
                        "maxTokensField": "max_tokens",
                    },
                    "thinkingLevelMap": {
                        "off": None,
                        "minimal": None,
                        "low": None,
                        "medium": None,
                        "high": "high",
                        "xhigh": None,
                        "max": "max",
                    },
                },
                {
                    "id": "kimi-k2.7-code",
                    "name": "Kimi K2.7 Code",
                    "reasoning": True,
                    "input": ["text", "image"],
                    "contextWindow": 262144,
                    "maxTokens": 262144,
                    "compat": {
                        "supportsStore": False,
                        "supportsDeveloperRole": False,
                        "maxTokensField": "max_tokens",
                    },
                    "thinkingLevelMap": {},
                },
                {
                    "id": "deepseek-v4-pro",
                    "name": "DeepSeek V4 Pro",
                    "reasoning": True,
                    "input": ["text"],
                    "contextWindow": 1000000,
                    "maxTokens": 384000,
                    "compat": {
                        "supportsStore": False,
                        "supportsDeveloperRole": False,
                        "maxTokensField": "max_tokens",
                        "requiresReasoningContentOnAssistantMessages": True,
                        "thinkingFormat": "deepseek",
                    },
                    "thinkingLevelMap": {
                        "minimal": None,
                        "low": None,
                        "medium": None,
                        "high": "high",
                        "max": "max",
                    },
                },
                {
                    "id": "deepseek-v4-flash",
                    "name": "DeepSeek V4 Flash",
                    "reasoning": True,
                    "input": ["text"],
                    "contextWindow": 1000000,
                    "maxTokens": 384000,
                    "compat": {
                        "supportsStore": False,
                        "supportsDeveloperRole": False,
                        "maxTokensField": "max_tokens",
                        "requiresReasoningContentOnAssistantMessages": True,
                        "thinkingFormat": "deepseek",
                    },
                    "thinkingLevelMap": {
                        "minimal": None,
                        "low": None,
                        "medium": None,
                        "high": "high",
                        "max": "max",
                    },
                },
            ],
        },
    },
    {
        "id": "custom",
        "name": "Custom Provider",
        "category": "custom",
        "website_url": None,
        "icon": None,
        "icon_color": None,
        "settings_config": {
            "name": "Custom Provider",
            "baseUrl": "https://api.example.com/v1",
            "api": "openai-completions",
            "apiKey": "",
            "models": [{"id": "your-model"}],
        },
    },
]
